inference: False
base:
  n_folds: 4
  num_boost_round: 2000
  seed: 1234
  submit: true
  optuna: true

parameters:
  objective: "regression"
  metric: "rmse"
  num_leaves: 31
  max_depth: 7
  learning_rate: .05
  # feature_fraction: 0.5
  verbose: -1